# General settings
baseURL = "https://markheydon.github.io/the-teachings-of-monkey/"
canonifyURLs = true
languageCode = "en-gb"
theme = "PaperMod"
title = "The Teachings of Monkey"
copyright = "Irrepressible since 2025 Â· [Mark Heydon](https://github.com/markheydon)"

# Menu entries
[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "about/"
    weight = 1

  [[menu.main]]
    identifier = "episodes"
    name = "Episodes"
    url = "episodes/"
    weight = 2

  [[menu.main]]
    identifier = "themes"
    name = "Themes"
    url = "themes/"
    weight = 3

  [[menu.main]]
    identifier = "extras"
    name = "Extras"
    url = "extras/"
    weight = 4

[params.footer]
  text = "[Repo](https://github.com/markheydon/the-teachings-of-monkey/)"
